#! /bin/sh -e
#

if [ -f /USING_COPR ]; then
 echo "---------------------- This is using a COPR DNF ----------------------"
 echo "DNF: https://copr.fedorainfracloud.org/coprs/mhatina/DNF-Modules/"
 if [ "x$1" = "xall" ]; then
    dnf --showdup list dnf libdnf
 else
    dnf --disablerepo=\* list installed dnf libdnf
 fi
 rpm -q --qf '%{name} Built on: %{buildtime:date}\n' libdnf
 rpm -q --qf '%{name}    Built on: %{buildtime:date}\n' dnf
 echo "----------------------------------------------------------------------"
else
 echo "------------------------------- DNF ----------------------------------"
 if [ "x$1" = "xall" ]; then
    dnf --showdup list dnf libdnf
 else
    dnf --disablerepo=\* list installed dnf libdnf
 fi
 echo "----------------------------------------------------------------------"
fi

 echo "Image built with (KOJI composes):"
 echo -e "\t\tGIT:      \thttps://github.com/container-images/boltron-27"
 echo -e "\t\tBase:     \t$(cat latest-Fedora-Modular-27.COMPOSE_ID)"
 echo -e "\t\tBikeshed: \t$(cat latest-Fedora-Modular-Bikeshed.COMPOSE_ID)"
 echo "Image running aginst (KOJI Composes):"
 echo -e "\t\tBase:     \t$(curl -s https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-27/COMPOSE_ID)"
 echo -e "\t\tBikeshed: \t$(curl -s https://kojipkgs.fedoraproject.org/compose/latest-Fedora-Modular-Bikeshed/COMPOSE_ID)"
 echo "Image running aginst (Modularity server):"
 echo -e "  http://modularity.fedorainfracloud.org/modularity/hack-fedora-f27-mods/..."
 echo -e "\t\tMaven:    \tmaven-@master-20170923133034"
 echo -e "\t\tMySQL:    \tmysql-@master-20170904221942"
 echo -e "\t\tninja:    \tninja-@master-20170904182925"
 echo -e "\t\tnodejs:   \tnodejs-@6-20170925160215"
 echo -e "\t\tnodejs:   \tnodejs-@master-20170925073359"
